web:
    image: node:0.12
    links:
        - mysql
    volumes_from:
        - src
    ports: 
        - "3000:3000"
    working_dir: /src/web
    stdin_open: true
    tty: true
scraper:
    image: node:0.12
    links: 
        - mysql
    volumes_from: 
        - src
    working_dir: /src/scraper
    stdin_open: true
    tty: true
src:
    image: ubuntu
    volumes: 
        - ./:/src