scraper:
    build: scraper/
    links: 
        - mysql
    volumes_from: 
        - src
mysql:
    build: ./mysql
    volumes_from: 
        - volume
volume:
    image: mysql
    volumes: 
        - /var/lib/mysql/
src:
    image: ubuntu
    volumes: 
        - /Users/Rutger/Dropbox/Projects/edubeaver/scraper:/src